import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[font]
size = 10.0

[font.normal]
family = "JetBrains Mono"
style = "Bold"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[window]
opacity = 0.8
